server:
  port: 8080

spring:
    datasource:
        url: jdbc:mysql://db_users.cloud-ip.net:3306/testdb?useUnicode=true&useSSL=false&characterEncoding=UTF-8&createDatabaseIfNotExist=true&autoReconnect=true&serverTimezone=UTC
        username: invper
        password: Il8


debug: false
